import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './component/navbar'
import MyProfilePic from './component/MyProfilePic'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kazim;s Blog',
  description: 'Generated by Kazim Hussain',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <Navbar/>
        <MyProfilePic/>
        {children}</body>
    </html>
  )
}
